export const googleResponse = (data: any) => ({
  address: "",
  bio: "",
  created_at: data?.user?.reloadUserInfo?.createdAt,
  gender: "",
  id: data?.user?.reloadUserInfo?.uid,
  ip_address: "",
  is_active: data?._tokenResponse?.emailVerified,
  latitude: "",
  location: "",
  longitude: "",
  profile_image_url: data?.user?.reloadUserInfo?.photoUrl,
  provider_id: data?.providerId,
  provider_name: "google",
  telephone: data?.user?.providerData?.[0]?.phoneNumber,
  theme: false,
  user: {
    id: data?.user?.reloadUserInfo?.uid,
    profile_id: data?.user?.reloadUserInfo?.uid,
    token: data?.user?.accessToken,
    created_at: data?.user?.reloadUserInfo?.createdAt,
    email: data?.user?.email,
    email_verified_at: data?._tokenResponse?.emailVerified,
    user_type: "USER",
    role_id: 1,
    updated_at: data?.user?.reloadUserInfo?.createdAt,
  },
  user_id: 18,
  walletBalance: 0,
  role_id: 1,
});
